name: R2 Prize
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26041932310909033
title: 'R2 Prize Initiative '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07060c'
    - '#00abdf'
    - '#259bc3'
    - '#043754'
    - '#1c6888'
  brandStrength: 0.4290967194829136
  lightness: 0.8781617830973119
  saturation: 0.7111734270583838
  rhythmicContrast: 0.3881421883124858
purpose: []
